[workspace]
authors = ["Manuel Saelices <msaelices@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "playground"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
modular = ">=25.7.0.dev2025102505,<26"
max = ">=25.7.0.dev2025102505,<26"
